import { appBarHeight } from "~/utils";
import type { AppsData } from "~/types";

const apps: AppsData[] = [
  {
    id: "finder",
    title: "Finder",
    desktop: true,
    width: 900,
    height: 560,
    minWidth: 600,
    minHeight: 380,
    x: -20,
    y: -20,
    img: "img/icons/finder.png",
    mobileTitle: "Files",
    mobileImg: "img/icons/folder-generic.png",
    content: <Finder />,
  },
  {
    id: "bear",
    title: "Bear",
    desktop: true,
    width: 860,
    height: 500,
    show: true,
    hideOnMobile: true,
    y: -40,
    img: "img/icons/bear.png",
    content: <Bear />,
  },
  {
    id: "typora",
    title: "Typora",
    desktop: true,
    width: 600,
    height: 580,
    hideOnMobile: true,
    y: -20,
    img: "img/icons/typora.png",
    content: <Typora />,
  },
  {
    id: "safari",
    title: "Safari",
    desktop: true,
    width: 1024,
    minWidth: 375,
    minHeight: 200,
    x: -20,
    img: "img/icons/safari.png",
    dockOnMobile: true,
    content: <Safari />,
  },
  {
    id: "vscode",
    title: "VSCode",
    desktop: true,
    width: 900,
    height: 600,
    hideOnMobile: true,
    x: 80,
    y: -30,
    img: "img/icons/vscode.png",
    content: <VSCode />,
  },
  {
    id: "facetime",
    title: "FaceTime",
    desktop: true,
    img: "img/icons/facetime.png",
    width: 500 * 1.7,
    height: 500 + appBarHeight,
    minWidth: 350 * 1.7,
    minHeight: 350 + appBarHeight,
    aspectRatio: 1.7,
    x: -80,
    y: 20,
    dockOnMobile: true,
    content: <FaceTime />,
  },
  {
    id: "terminal",
    title: "Terminal",
    desktop: true,
    hideOnMobile: true,
    img: "img/icons/terminal.png",
    width: 720,
    height: 480,
    minWidth: 420,
    minHeight: 280,
    x: -20,
    y: -20,
    content: <Terminal />,
  },

  {
    id: "github",
    title: "Github",
    desktop: false,
    hideOnMobile: true,
    img: "img/icons/github.png",
    link: "https://github.com/vishnums2k5",
  },
  {
    id: "spotify",
    title: "Spotify",
    desktop: true,
    width: 860,
    height: 500,
    show: false,
    hideOnMobile: true,
    y: -40,
    titlebar: "transparent",
    img: "img/icons/spotify.png",
    content: <Spotify />,
  },
  {
    id: "siri",
    title: "Siri",
    desktop: true,
    width: 860,
    height: 500,
    show: false,
    hideOnMobile: true,
    y: -40,
    img: "img/icons/siri.png",
    content: <Siri />,
  },
  {
    id: "calculator",
    title: "Calculator",
    desktop: true,
    width: 280,
    height: 420,
    x: 40,
    y: 20,
    img: "img/icons/calculator.png",
    content: <Calculator />,
  },
  {
    id: "system-settings",
    title: "System Settings",
    desktop: true,
    width: 720,
    height: 520,
    minWidth: 580,
    minHeight: 420,
    x: -40,
    y: 10,
    img: "img/icons/settings.png",
    mobileTitle: "Settings",
    content: <SystemSettings />,
  },
  {
    id: "notes",
    title: "Notes",
    desktop: true,
    width: 720,
    height: 480,
    minWidth: 480,
    minHeight: 340,
    x: 30,
    y: -10,
    img: "img/icons/notes.png",
    content: <Notes />,
  },
  {
    id: "music",
    title: "Music",
    desktop: true,
    width: 780,
    height: 500,
    minWidth: 580,
    minHeight: 380,
    x: -30,
    y: 20,
    img: "img/icons/music.png",
    dockOnMobile: true,
    content: <Music />,
  },
  {
    id: "maps",
    title: "Maps",
    desktop: true,
    width: 800,
    height: 520,
    minWidth: 600,
    minHeight: 400,
    x: 20,
    y: -30,
    img: "img/icons/maps.png",
    content: <Maps />,
  },
  {
    id: "messages",
    title: "Messages",
    desktop: true,
    width: 740,
    height: 500,
    minWidth: 560,
    minHeight: 380,
    x: -50,
    y: 10,
    img: "img/icons/messages.png",
    dockOnMobile: true,
    content: <Messages />,
  },
  {
    id: "photos",
    title: "Photos",
    desktop: true,
    width: 820,
    height: 540,
    minWidth: 620,
    minHeight: 420,
    x: 40,
    y: -20,
    img: "img/icons/photos.png",
    content: <Photos />,
  },
  {
    id: "clock",
    title: "Clock",
    desktop: true,
    width: 420,
    height: 560,
    minWidth: 340,
    minHeight: 440,
    x: -20,
    y: 10,
    img: "img/icons/clock.png",
    content: <Clock />,
  },
  {
    id: "mail",
    title: "Mail",
    desktop: true,
    width: 860,
    height: 540,
    minWidth: 640,
    minHeight: 400,
    x: 20,
    y: -10,
    img: "img/icons/mail.png",
    content: <Mail />,
  },
  {
    id: "app-store",
    title: "App Store",
    desktop: true,
    width: 760,
    height: 540,
    minWidth: 580,
    minHeight: 420,
    x: -30,
    y: 20,
    img: "img/icons/app-store.png",
    content: <AppStore />,
  },
  {
    id: "youtube",
    title: "YouTube",
    desktop: true,
    hideFromDock: true,
    hideOnMobile: true,
    width: 900,
    height: 600,
    minWidth: 600,
    minHeight: 400,
    x: 30,
    y: -30,
    titlebar: "transparent",
    img: "img/icons/YouTube_3I5Pfpsd8t.png",
    content: <YouTube />,
  },
];

export default apps;
